class GeneralAttorny {
  late String ownerName;
  late String ownerFatherName;
  late String ownerCast;
  late String ownerLocation;
  late String ownerTahseel;
  late String ownerDistrict;
  late String ownerIDCardNo;
  late String khataNo;
  late String khatoniNo;
  late String nambratKhasra;
  late String katat;
  late String areaTransfer;
  late String totalArea;
  late String totalTransferArea;
  late String currentLocation;
  late String locationTahseel;
  late String locationDistrict;
  late String executerName;
  late String executerFatherName;
  late String executerCast;
  late String executerLocation;
  late String executerTahseel;
  late String executerDistrict;
}
